const fs=require('node:fs');
const assert=require('node:assert/strict');
const js=fs.readFileSync('assets/js/market.js','utf8');
const css=fs.readFileSync('assets/css/main.css','utf8');
const html=fs.readFileSync('market.html','utf8');
assert(js.includes('function listingTrendHTML(row)'));
assert(js.includes('Number.isFinite(Number(value))'));
assert(js.includes("amount > 0 ? 'up' : amount < 0 ? 'down' : 'neutral'"));
assert(js.includes("amount > 0 ? '↑' : amount < 0 ? '↓' : '→'"));
assert(js.includes('Source-reported 1Y asking-price change'));
assert(js.includes('class="market-asking-range"'));
assert(js.includes('market-trend-cell" data-label-vi="Biến động 1 năm"'));
assert(js.includes('projectTable(data.projects, 8)'));
assert(js.includes('View all ${data.projects.length} projects'));
for(const c of ['.market-trend--up','.market-trend--down','.market-trend--neutral','.market-asking-range'])assert(css.includes(c));
assert(html.includes('scan4J2=1'));
const samples=JSON.parse(fs.readFileSync('data/mock/market/listing-observations.json','utf8')).data;
assert(samples.some(x=>Number(x.asking_price_change_1y_pct)>0));
assert(samples.some(x=>Number(x.asking_price_change_1y_pct)<0));
assert(samples.some(x=>x.asking_price_change_1y_pct==null));
console.log('PASS 4J.2: preserve reported market trends, highlight current snapshots, and show eight projects');
