const fs=require('node:fs'),assert=require('node:assert/strict');
const legal=fs.readFileSync('assets/js/legal.js','utf8');
const infra=fs.readFileSync('assets/js/infrastructure.js','utf8');
const macro=fs.readFileSync('assets/js/macro.js','utf8');
const css=fs.readFileSync('assets/css/main.css','utf8');
const docs=JSON.parse(fs.readFileSync('data/mock/legal/documents.json','utf8'));
const projects=JSON.parse(fs.readFileSync('data/mock/infrastructure/projects.json','utf8'));
assert(docs.data.length>=10 && projects.data.length>=8);
assert(legal.includes("module: 'legal'"));
assert(infra.includes("module: 'infrastructure'"));
assert(macro.includes("module: 'macro'"));
assert(legal.includes('data-document-id'));
assert(legal.includes('MarketNewsUI.render'));
assert(infra.includes('Math.min(8,data.infrastructureProjects.length)'));
assert(infra.includes('infra-milestone-grid'));
assert(infra.includes('MarketNewsUI.render'));
assert(macro.includes('function indicatorCadence(row)'));
assert(macro.includes("row.period_type === 'month'"));
assert(macro.includes("row.period_type === 'day'"));
assert(macro.includes('function latestProductionReleaseList(limit=5)'));
assert(macro.includes("row._data_layer === 'production'"));
assert(macro.includes('macro-overview-cadence-note'));
assert(!macro.includes('<h2 class="section-title">Illustrative Developments</h2>'));
for(const cls of ['infra-milestone-grid','article-list--infra-compact','article-list--legal-official','macro-cadence'])assert(css.includes(cls));
for(const file of ['legal.html','infrastructure.html','macro.html'])assert(fs.readFileSync(file,'utf8').includes('density=4J3'));
console.log('PASS 4J.3: official document updates, eight infrastructure projects, compact milestones and dated production macro releases');
