const fs=require('node:fs');
const assert=require('node:assert/strict');
const store=fs.readFileSync('assets/js/data-store.js','utf8');
const market=fs.readFileSync('assets/js/market.js','utf8');
const workflow=fs.readFileSync('.github/workflows/market-rever-verified-listings.yml','utf8');
assert.ok(store.includes("getReverVerifiedUnitListings: () => loadJSON('market/verified-unit-listings.json')"));
assert.ok(market.includes("DataStore.getReverVerifiedUnitListings().catch(() => ({data:[]}))"));
assert.ok(market.includes("item.review_status === 'automated-two-hosted-checks'"));
assert.ok(market.includes("item.metric_type === 'single-listing-asking-price-per-sqm'"));
assert.ok(market.includes("item.asset_type === 'apartment'"));
assert.ok(market.includes("90 * 86400000"));
assert.ok(market.includes("existing.length >= 2"));
assert.ok(market.includes("existing.some(row => row.listing_id === item.listing_id && row.source_id === item.source_id)"));
assert.ok(market.includes("...currentUnitOffers"));
assert.ok(market.includes("Ngày cập nhật tin"));
assert.ok(market.includes("không đại diện giá bình quân dự án"));
assert.ok(market.includes("group.id === 'listing' && groupRows[group.id].length > 3"));
const zone=market.slice(market.indexOf('function listingRangeChartData'),market.indexOf('function priceLayerControls'));
assert.ok(!zone.includes('reverVerifiedUnitListings'),'Never contaminate portal project chart');
assert.ok(workflow.includes('market-rever-verified-listings'));
console.log('PASS: live Rever single-listing source stays recent, capped, separated from prices and collapsed when numerous');

const maintenance=fs.readFileSync('assets/js/maintenance.js','utf8');
const rever=fs.readFileSync('scripts/market_rever_project_listings.py','utf8');
assert.ok(maintenance.includes("data/state/market-rever-source-health.json"));
assert.ok(maintenance.includes("source_updates_within_90_days"));
assert.ok(maintenance.includes("published_current_individual_listings"));
assert.ok(rever.includes('publish=not pr_preview'));
assert.ok(rever.includes('if not pr_preview:'));
assert.ok(rever.includes('source_health(report, state, prod)'));
console.log('PASS: Rever read-only source freshness monitoring stays separate from verified prices');
