const fs=require('node:fs');
const assert=require('node:assert/strict');
const store=fs.readFileSync('assets/js/data-store.js','utf8');
const market=fs.readFileSync('assets/js/market.js','utf8');
const maintenance=fs.readFileSync('assets/js/maintenance.js','utf8');
const scanner=fs.readFileSync('scripts/market_muaban_verified_listings.py','utf8');
const workflow=fs.readFileSync('.github/workflows/market-muaban-live-listings.yml','utf8');

assert(store.includes("getMuabanVerifiedUnitListings: () => loadJSON('market/verified-muaban-unit-listings.json')"));
assert(market.includes('...data.reverVerifiedUnitListings, ...data.muabanVerifiedUnitListings'));
assert(market.includes("Date.parse(item.source_expiration_date + 'T23:59:59+07:00')"));
assert(market.includes('row.source_date_basis === "publisher-listing-start-not-update"'));
assert(market.includes("'muaban-vn':'Muaban.net'"));
assert(market.includes('existing.length >= 2 || existing.some'));
assert(market.includes('item.review_status === \'automated-two-hosted-checks\''));
const chart=market.slice(market.indexOf('function listingRangeChartData'),market.indexOf('function priceLayerControls'));
assert(!chart.includes('muabanVerifiedUnitListings'));
assert(!chart.includes('reverVerifiedUnitListings'));
assert(maintenance.includes('data/state/market-muaban-source-health.json'));
assert(maintenance.includes('valid_unexpired_project_ads'));
assert(maintenance.includes('published_current_individual_listings'));
assert(scanner.includes('pr = os.environ.get("GITHUB_EVENT_NAME") == "pull_request"'));
assert(scanner.includes('publish=not pr'));
assert(scanner.includes('if not pr:'));
assert(scanner.includes('now.date() > expiry'));
assert(scanner.includes('start > now.date()'));
assert(workflow.includes("if: github.event_name == 'pull_request'"));
assert(workflow.includes("git diff --exit-code -- data/mock/market/verified-muaban-unit-listings.json"));
assert(!JSON.parse(fs.readFileSync('data/mock/market/verified-muaban-unit-listings.json')).record_count);
console.log('PASS: Muaban source strictly expiry-gated, per-unit only, no PR publication, no project ASP contamination');
