const fs=require("node:fs");
const assert=require("node:assert/strict");
const home=fs.readFileSync("index.html","utf8");
const logic=fs.readFileSync("assets/js/home.js","utf8");
const components=fs.readFileSync("assets/js/components.js","utf8");
const loc=fs.readFileSync("assets/js/localization-static.js","utf8");
assert(!home.includes('class="demo-banner"'));
assert(!home.includes('class="home-snapshot"'));
assert(home.indexOf('aria-labelledby="today-title"') < home.indexOf('aria-labelledby="data-health-title"'));
assert(home.includes('class="home-more-history"'));
assert(home.includes('data-home-top-developments'));
assert(home.includes('data-home-weekly'));
assert(home.includes('data-home-indicators'));
assert(home.includes('home4J1=1'));
assert(logic.includes('for (const source of [recent, extended, older])'));
assert(logic.includes('const recent = within(7), extended = within(90), older = within(365)'));
assert(logic.includes('if (row.category !== category || picked.length >= 3) continue'));
assert(logic.includes("date_label: item.date_label || App.formatDate(item.sort_date)"));
assert(logic.includes("row.period_type === 'month' ? 'Monthly'"));
assert(logic.includes("const priority = ['usd-vnd-central-rate','sjc-gold-sell'"));
assert(logic.includes('if (shortlist.length >= 4) break'));
assert(components.includes('(group.items || []).slice(0, 3)'));
assert(components.includes('item.date_label'));
assert(components.includes('item.cadence_label'));
assert(loc.includes("['#today-title', 'Latest Updates', 'Cập nhật mới nhất']"));
console.log('PASS: compact home has real dated latest entries, four macro cards and expandable history');
